#!/usr/bin/env python3
"""
Build script — freeze keylogger_detector.py into a standalone Windows .exe.

    python build.py                # release build (embeds the UAC elevation request)
    python build.py --no-uac       # local test build, runs without an elevation prompt
    python build.py --resources-only   # regenerate version/manifest resources, don't build

Output: dist/keylogger-detector.exe — one self-contained binary, no Python
installation required on the target machine.

Requires the dev toolchain:  pip install -r requirements-dev.txt

Icon: drop a multi-resolution (256x256) icon at assets/icon.ico and it is picked
up automatically. The build deliberately still succeeds without one.
"""

import argparse
import hashlib
import os
import platform
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ENTRY_SCRIPT = os.path.join(HERE, "keylogger_detector.py")
ICON_PATH = os.path.join(HERE, "assets", "icon.ico")

# Generated build inputs live outside build/ on purpose: PyInstaller's --clean
# wipes build/ at startup, which would delete them before they are read.
RESOURCE_DIR = os.path.join(HERE, "build_resources")
VERSION_FILE = os.path.join(RESOURCE_DIR, "version_info.txt")
MANIFEST_FILE = os.path.join(RESOURCE_DIR, "uac_admin.manifest")

APP_NAME = "keylogger-detector"
PRODUCT_NAME = "Keylogger Detector"
DESCRIPTION = "Heuristic Keylogger Detector"
COMPANY_NAME = "JEMS PATEL"
COPYRIGHT = "Copyright (c) 2026 JEMS PATEL. Released under the MIT License."

VERSION_TEMPLATE = """# UTF-8
#
# Generated by build.py -- do not edit. Windows VERSIONINFO resource embedded
# into the .exe so that File Properties -> Details shows real metadata instead
# of a blank, anonymous binary.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vers},
    prodvers={vers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'{company}'),
        StringStruct(u'FileDescription', u'{description}'),
        StringStruct(u'FileVersion', u'{version}'),
        StringStruct(u'InternalName', u'{app_name}'),
        StringStruct(u'LegalCopyright', u'{copyright}'),
        StringStruct(u'OriginalFilename', u'{app_name}.exe'),
        StringStruct(u'ProductName', u'{product}'),
        StringStruct(u'ProductVersion', u'{version}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""

# Requests the standard Windows elevation consent prompt at launch.
# requireAdministrator = the OS asks the user, visibly, every time. We do NOT
# auto-elevate, re-spawn via ShellExecute "runas", or suppress the prompt.
MANIFEST_TEMPLATE = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity type="win32" name="{app_name}" version="{version}"
                    processorArchitecture="*"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!-- Windows 10 / 11 -->
      <supportedOS Id="{{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}}"/>
      <!-- Windows 8.1 -->
      <supportedOS Id="{{1f676c76-80e1-4239-95bb-83d0f6d0da78}}"/>
      <!-- Windows 7 -->
      <supportedOS Id="{{35138b9a-5d96-4fbd-8e2d-a2440225f93a}}"/>
    </application>
  </compatibility>
</assembly>
"""


def read_version():
    """Read __version__ from keylogger_detector.py by parsing, not importing.

    Parsing keeps build.py dependency-free (it does not need psutil present)
    and avoids executing the module as a side effect of building it.
    """
    try:
        with open(ENTRY_SCRIPT, "r", encoding="utf-8") as fh:
            source = fh.read()
    except OSError as exc:
        sys.exit(f"ERROR: cannot read {ENTRY_SCRIPT}: {exc}")
    match = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']', source, re.M)
    if not match:
        sys.exit("ERROR: no __version__ found in keylogger_detector.py")
    return match.group(1)


def version_tuple(version):
    """'1.0.0' -> (1, 0, 0, 0): the Windows resource needs exactly four ints."""
    parts = []
    for chunk in version.split("."):
        digits = re.match(r"\d+", chunk)
        parts.append(int(digits.group(0)) if digits else 0)
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])


def write_resources(version):
    """Generate the VERSIONINFO and UAC manifest inputs. Returns their paths."""
    os.makedirs(RESOURCE_DIR, exist_ok=True)
    vers = version_tuple(version)

    with open(VERSION_FILE, "w", encoding="utf-8") as fh:
        fh.write(VERSION_TEMPLATE.format(
            vers=vers, version=version, app_name=APP_NAME, product=PRODUCT_NAME,
            description=DESCRIPTION, company=COMPANY_NAME, copyright=COPYRIGHT))

    with open(MANIFEST_FILE, "w", encoding="utf-8") as fh:
        fh.write(MANIFEST_TEMPLATE.format(
            app_name=APP_NAME, version=".".join(str(p) for p in vers)))

    return VERSION_FILE, MANIFEST_FILE


def sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(131072), b""):
            digest.update(block)
    return digest.hexdigest()


def ensure_pyinstaller():
    try:
        import PyInstaller  # noqa: F401
        return PyInstaller.__version__
    except ImportError:
        sys.exit("ERROR: PyInstaller is not installed.\n"
                 "       Install the build toolchain first:\n"
                 "           pip install -r requirements-dev.txt")


def main():
    parser = argparse.ArgumentParser(
        description="Freeze keylogger_detector.py into a standalone Windows .exe")
    parser.add_argument("--no-uac", action="store_true",
                        help="Build WITHOUT the administrator elevation request. For local "
                             "testing only (an elevated exe opens its own console, so its "
                             "stdout cannot be captured by a normal shell). Never ship this.")
    parser.add_argument("--resources-only", action="store_true",
                        help="Only regenerate build_resources/, then exit")
    parser.add_argument("--allow-non-windows", action="store_true",
                        help="Run PyInstaller on a non-Windows host anyway (produces a "
                             "native binary, NOT a .exe -- PyInstaller cannot cross-compile)")
    args = parser.parse_args()

    version = read_version()
    print(f"{PRODUCT_NAME} {version} -- build")

    if platform.system() != "Windows" and not args.allow_non_windows:
        sys.exit(f"ERROR: this produces a Windows .exe, but the host is {platform.system()}.\n"
                 "       PyInstaller cannot cross-compile: build on Windows (or in a Windows\n"
                 "       CI runner / VM). Use --allow-non-windows to build a native binary.")

    version_file, manifest_file = write_resources(version)
    print(f"  version resource -> {os.path.relpath(version_file, HERE)}")
    if args.no_uac:
        print("  manifest         -> SKIPPED (--no-uac: test build, no elevation prompt)")
    else:
        print(f"  manifest         -> {os.path.relpath(manifest_file, HERE)} "
              "(requireAdministrator)")

    if args.resources_only:
        print("Resources written. Skipping build (--resources-only).")
        return 0

    pyi_version = ensure_pyinstaller()
    print(f"  PyInstaller      -> {pyi_version}")

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onefile",                      # one self-contained exe, no _internal folder
        "--console",                      # CLI tool: keep the terminal window
        "--name", APP_NAME,
        "--version-file", version_file,
        "--hidden-import", "psutil",
        "--clean", "--noconfirm",
        "--log-level", "WARN",
    ]

    if not args.no_uac:
        # --uac-admin sets requestedExecutionLevel; the explicit manifest also
        # carries the supportedOS compatibility block. Both are idempotent.
        cmd += ["--uac-admin", "--manifest", manifest_file]

    if os.path.isfile(ICON_PATH):
        cmd += ["--icon", ICON_PATH]
        print(f"  icon             -> {os.path.relpath(ICON_PATH, HERE)}")
    else:
        print(f"  icon             -> none (put a .ico at {os.path.relpath(ICON_PATH, HERE)} "
              "to brand the exe)")

    cmd.append(ENTRY_SCRIPT)

    print("\n$ " + " ".join(cmd) + "\n")
    result = subprocess.run(cmd, cwd=HERE)
    if result.returncode != 0:
        return result.returncode

    exe_path = os.path.join(HERE, "dist", APP_NAME + (".exe" if platform.system() == "Windows" else ""))
    if not os.path.isfile(exe_path):
        sys.exit(f"ERROR: PyInstaller reported success but {exe_path} is missing")

    size_mb = os.path.getsize(exe_path) / (1024 * 1024)
    print(f"\nBuilt {os.path.relpath(exe_path, HERE)}  ({size_mb:.1f} MB)")
    print(f"SHA-256: {sha256(exe_path)}")
    if args.no_uac:
        print("\nNOTE: test build -- no elevation request embedded. Rebuild without "
              "--no-uac before releasing.")
    else:
        print("\nLaunching it will show the standard Windows UAC consent prompt.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
